[Add][RSpec編]taskモデルのバリデーションに関するテスト実装
kazuki13070311/sample_app_for_rspec pull request #2
Opened 2021-01-06 16:11 UTC by kazuki13070311

## 概要
 - taskモデルのバリデーションに関するテストの実装を行った

## 内容
- taskモデルを参照しバリデーションに関するテストコードを追記した
- テストデータの作成にはFactoryBotを使用した

2021-01-08 04:46 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status {1}
1だとどんなステータスが入るか、このファイルを見ても分からないですね

2021-01-08 04:46 UTC, yuji91 commented on spec/factories/tasks.rb
> +    content {'サンプル'}
スペースで開けた方が見やすいかと思います。
```suggestion
    content { 'サンプル' }
```

2021-01-08 04:47 UTC, yuji91 requested changes
細かい2点指摘しました！

2021-01-08 11:16 UTC, kazuki13070311 commented on spec/factories/tasks.rb
> +    status {1}
ステータスに入るものがこのファイル内だけで分かるよう修正しました。

2021-01-08 11:16 UTC, kazuki13070311 commented on spec/factories/tasks.rb
> +    content {'サンプル'}
スペースを追加しました。

2021-01-12 09:10 UTC, kazuki13070311 commented on spec/factories/tasks.rb
> +    status {1}
fb424f9 ステータスに入るものがこのファイル内だけで分かるよう修正しました

2021-01-12 09:10 UTC, kazuki13070311 commented on spec/factories/tasks.rb
> +    content {'サンプル'}
2bd5617 スペースを追加しました

2021-01-12 09:14 UTC, yuji91 approved these changes
LGTMです！

2021-01-12 12:51 UTC, merged